# Generated by Django 5.0.6 on 2024-06-27 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="wallet_id",
            new_name="wallet",
        ),
    ]
